# Generated by Django 2.0.6 on 2019-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Salary', models.CharField(max_length=20)),
                ('Age', models.SmallIntegerField()),
                ('Birthday', models.DateField()),
                ('Headpic', models.ImageField(upload_to='pics')),
            ],
            options={
                'db_table': 'my_employee',
            },
        ),
    ]
