# Generated by Django 2.0.6 on 2019-06-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Headpic',
            new_name='headpic',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Salary',
            new_name='salary',
        ),
    ]
