# Generated by Django 2.0.6 on 2019-06-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_auto_20190627_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hobby',
        ),
        migrations.AddField(
            model_name='employee',
            name='headpic',
            field=models.ImageField(default='xx', upload_to='pics'),
        ),
    ]
